trigger: none

pr: none #will disable PR builds entirely; will not disable CI triggers

resources:
  pipelines:
  - pipeline: ciartifacts
    source: mdwdo-park-ci-artifacts
    trigger: 
      branches:
      - master
  repositories:
  - repository: mdwdataops_adfpublish
    type: github
    endpoint: mdwdo-park-github
    name: darkanita/mdw-dataops-clone
    ref: adf_publish